### ISSUE TITLE
PoC: Authentication

### ISSUE THREAD

**Issue by mikz** [3scale/ostia#14]
TBD

**Comment by PhilipGough** [comment]
In regards to the CRD, I was thinking we might handle this similar to the way we did we rate limits. For example:

```yaml
authentication:
- type: OIDC
   url: www.example.com
- type: BasicAuth
   secretRef: some-secret
.....
```
Basically, have a top level Authentication object which is a placeholder for multiple authn types and their related params. This allows it to be moved into its own CRD at a later date if that was beneficial.
