### ISSUE TITLE
Ostia Configuration

### ISSUE THREAD

**Issue by mikz** [3scale/ostia#68]
After the #67 we can implement a Controller to configure & deploy Ostia components.

I believe, there is a value in local development and having ultra-fast feedback and the ability to debug on a local machine. For that, I think the first iteration could be just a simple mapper of yaml files into different yaml configs (for each component). And using simple shell utilities to restart components when configs change. That can be later extended into full OpenShift controller that deploys components too (if someone feels like using that for development or we need to do a demo).

However, the simplest way of configuring components, for now,  is in my opinion YAML file for each component. Not using any kind of DB will make things easier in the beginning.

**Comment by mikz** [comment]
# Storing Application (Client) data

Apps/Clients can have API keys or enabled/disabled state. Enabled some modes of authentication or attached permissions. These objects can be stored in IDP or somewhere else.

When there is no self-service needed the objects can be stored in k8s and managed by the users that have access to the cluster. CRs for these apps can be later used by the #65 or synced to IDP by some other operator.

Example:

```yaml
kind: OAuth2Client
version: v1.ostia.3scale.net
metadata:
  label: forsync
data:
  client_id: someclient
  client_secret: somesecret
  enabled: true

---

kind: ClientSync
version: v1.ostia.3scale.net
data:
  clients:
    labelSelector: forsync

  idp:
    labelSelector: keycloak-production


kind: APIClient
version: v1.ostia.3scale.net
data:
  api_key: somekey
  api_secret: secret
  enabled: true
  permissions: [ 'billing' ]
```


The #65 can read these CRs and use them directly for auth (like the APIClient) or use some operator to convert them to other CRs (eg. Keycloak) and use operators to sync them to the specific IDP.
